# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
               
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
  poetry-lint:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - name: lint
      run: poetry run task lint
  poetry-formater:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - name: formatter
      run: poetry run task formatter
  poetry-security:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - name: security
      run: poetry run task security
  poetry-test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - name: security
      run: poetry run task test
      
    
      
 #   - name: Poetry runy
 #     run: |
 #       poetry run task lint
 #       poetry run task formatter
 #       poetry run task security
 #       poetry run task test
